/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppHeader {
    'headerTitle': string;
  }
  interface AppHeaderAttributes extends StencilHTMLAttributes {
    'headerTitle'?: string;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppSubheader {
    'hasCreate': boolean;
    'hasTitle': boolean;
    'moreMenuComponent': string;
    'subheaderTitle': string;
  }
  interface AppSubheaderAttributes extends StencilHTMLAttributes {
    'hasCreate'?: boolean;
    'hasTitle'?: boolean;
    'moreMenuComponent'?: string;
    'subheaderTitle'?: string;
  }

  interface LocationDetail {}
  interface LocationDetailAttributes extends StencilHTMLAttributes {}

  interface LocationsList {}
  interface LocationsListAttributes extends StencilHTMLAttributes {}

  interface MaterialDetail {}
  interface MaterialDetailAttributes extends StencilHTMLAttributes {}

  interface MaterialsListMorePopover {}
  interface MaterialsListMorePopoverAttributes extends StencilHTMLAttributes {}

  interface MaterialsList {}
  interface MaterialsListAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHeader': Components.AppHeader;
    'AppHome': Components.AppHome;
    'AppRoot': Components.AppRoot;
    'AppSubheader': Components.AppSubheader;
    'LocationDetail': Components.LocationDetail;
    'LocationsList': Components.LocationsList;
    'MaterialDetail': Components.MaterialDetail;
    'MaterialsListMorePopover': Components.MaterialsListMorePopover;
    'MaterialsList': Components.MaterialsList;
  }

  interface StencilIntrinsicElements {
    'app-header': Components.AppHeaderAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-root': Components.AppRootAttributes;
    'app-subheader': Components.AppSubheaderAttributes;
    'location-detail': Components.LocationDetailAttributes;
    'locations-list': Components.LocationsListAttributes;
    'material-detail': Components.MaterialDetailAttributes;
    'materials-list-more-popover': Components.MaterialsListMorePopoverAttributes;
    'materials-list': Components.MaterialsListAttributes;
  }


  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSubheaderElement extends Components.AppSubheader, HTMLStencilElement {}
  var HTMLAppSubheaderElement: {
    prototype: HTMLAppSubheaderElement;
    new (): HTMLAppSubheaderElement;
  };

  interface HTMLLocationDetailElement extends Components.LocationDetail, HTMLStencilElement {}
  var HTMLLocationDetailElement: {
    prototype: HTMLLocationDetailElement;
    new (): HTMLLocationDetailElement;
  };

  interface HTMLLocationsListElement extends Components.LocationsList, HTMLStencilElement {}
  var HTMLLocationsListElement: {
    prototype: HTMLLocationsListElement;
    new (): HTMLLocationsListElement;
  };

  interface HTMLMaterialDetailElement extends Components.MaterialDetail, HTMLStencilElement {}
  var HTMLMaterialDetailElement: {
    prototype: HTMLMaterialDetailElement;
    new (): HTMLMaterialDetailElement;
  };

  interface HTMLMaterialsListMorePopoverElement extends Components.MaterialsListMorePopover, HTMLStencilElement {}
  var HTMLMaterialsListMorePopoverElement: {
    prototype: HTMLMaterialsListMorePopoverElement;
    new (): HTMLMaterialsListMorePopoverElement;
  };

  interface HTMLMaterialsListElement extends Components.MaterialsList, HTMLStencilElement {}
  var HTMLMaterialsListElement: {
    prototype: HTMLMaterialsListElement;
    new (): HTMLMaterialsListElement;
  };

  interface HTMLElementTagNameMap {
    'app-header': HTMLAppHeaderElement
    'app-home': HTMLAppHomeElement
    'app-root': HTMLAppRootElement
    'app-subheader': HTMLAppSubheaderElement
    'location-detail': HTMLLocationDetailElement
    'locations-list': HTMLLocationsListElement
    'material-detail': HTMLMaterialDetailElement
    'materials-list-more-popover': HTMLMaterialsListMorePopoverElement
    'materials-list': HTMLMaterialsListElement
  }

  interface ElementTagNameMap {
    'app-header': HTMLAppHeaderElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'app-subheader': HTMLAppSubheaderElement;
    'location-detail': HTMLLocationDetailElement;
    'locations-list': HTMLLocationsListElement;
    'material-detail': HTMLMaterialDetailElement;
    'materials-list-more-popover': HTMLMaterialsListMorePopoverElement;
    'materials-list': HTMLMaterialsListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
