/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface LocationDetail {}
  interface LocationDetailAttributes extends StencilHTMLAttributes {}

  interface LocationsList {}
  interface LocationsListAttributes extends StencilHTMLAttributes {}

  interface MaterialDetail {}
  interface MaterialDetailAttributes extends StencilHTMLAttributes {}

  interface MaterialsList {}
  interface MaterialsListAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppRoot': Components.AppRoot;
    'LocationDetail': Components.LocationDetail;
    'LocationsList': Components.LocationsList;
    'MaterialDetail': Components.MaterialDetail;
    'MaterialsList': Components.MaterialsList;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-root': Components.AppRootAttributes;
    'location-detail': Components.LocationDetailAttributes;
    'locations-list': Components.LocationsListAttributes;
    'material-detail': Components.MaterialDetailAttributes;
    'materials-list': Components.MaterialsListAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLLocationDetailElement extends Components.LocationDetail, HTMLStencilElement {}
  var HTMLLocationDetailElement: {
    prototype: HTMLLocationDetailElement;
    new (): HTMLLocationDetailElement;
  };

  interface HTMLLocationsListElement extends Components.LocationsList, HTMLStencilElement {}
  var HTMLLocationsListElement: {
    prototype: HTMLLocationsListElement;
    new (): HTMLLocationsListElement;
  };

  interface HTMLMaterialDetailElement extends Components.MaterialDetail, HTMLStencilElement {}
  var HTMLMaterialDetailElement: {
    prototype: HTMLMaterialDetailElement;
    new (): HTMLMaterialDetailElement;
  };

  interface HTMLMaterialsListElement extends Components.MaterialsList, HTMLStencilElement {}
  var HTMLMaterialsListElement: {
    prototype: HTMLMaterialsListElement;
    new (): HTMLMaterialsListElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-root': HTMLAppRootElement
    'location-detail': HTMLLocationDetailElement
    'locations-list': HTMLLocationsListElement
    'material-detail': HTMLMaterialDetailElement
    'materials-list': HTMLMaterialsListElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'location-detail': HTMLLocationDetailElement;
    'locations-list': HTMLLocationsListElement;
    'material-detail': HTMLMaterialDetailElement;
    'materials-list': HTMLMaterialsListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
